// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tekityyobzqjmrlqbyyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRla2l0eXlvYnpxam1ybHFieXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzY1MzgsImV4cCI6MjA2MzQxMjUzOH0.WXNPLLYowiQH4XyNkzYQgkyhdDIFwQkvjIeoHQqpKmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);